version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_db
    ports:
      - '5434:5432'  # Cambié el puerto local a 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
